#ifndef MON_SPLL_H
#define MON_SPLL_H

// will do as long as spell/sec numbers don't come above 255 or below 0:
/*
   Note: is assumed that most monsters capable of casting the more powerful
   summonings can also cast Abjuration (just for simplicity)
 */

// sec  bolt   ench  selfench  misc   misc2  emergency
/*orc wiz              */
    {0,
     MS_MMISSILE,
     MS_SLOW,
     MS_HASTE,
     MS_MMISSILE,
     100,
     MS_BLINK},
/*orc wiz              */
    {1,
     MS_FLAME,
     MS_CONFUSE,
     MS_INVIS,
     MS_MMISSILE,
     100,
     100},
/*orc wiz              */
    {2,
     MS_FROST,
     100,
     MS_HASTE,
     MS_FLAME,
     MS_MMISSILE,
     100},
/* guardian naga       */
    {10,
     MS_TELEPORT_OTHER,
     MS_TELEPORT_OTHER,
     MS_HEAL,
     MS_VENOM_BOLT,
     MS_SLOW,
     MS_HEAL},
/*Lich                 */
    {20,
     MS_COLD_BOLT,
     MS_PARALYSIS,
     MS_SUMMON_DEMON_GREATER,
     MS_ANIMATE_DEAD,
     MS_IRON_BOLT,
     MS_TELEPORT},
/*Lich                 */
    {21,
     MS_FIRE_BOLT,
     MS_CONFUSE,
     MS_HASTE,
     MS_NEGATIVE_BOLT,
     MS_SUMMON_DEMON_GREATER,
     MS_BANISHMENT},
/*Lich                 */
    {22,
     MS_NEGATIVE_BOLT,
     MS_ANIMATE_DEAD,
     MS_SUMMON_DEMON_GREATER,
     MS_FROST,
     MS_CRYSTAL_SPEAR,
     MS_BLINK},
/*Lich                 */
    {23,
     MS_ORB_ENERGY,
     MS_COLD_BOLT,
     MS_INVIS,
     MS_ANIMATE_DEAD,
     MS_IRON_BOLT,
     MS_INVIS},
/*burning devil        */
    {30,
     MS_HELLFIRE_BURST,
     MS_HELLFIRE_BURST,
     MS_HELLFIRE_BURST,
     MS_HELLFIRE_BURST,
     MS_HELLFIRE_BURST,
     MS_HELLFIRE_BURST},
/*vampire              */
    {40,        // gave these guys a bit more than "rats and bats" -- bwr
     MS_VAMPIRE_SUMMON,
     MS_CONFUSE,
     MS_INVIS,
     100,
     MS_VAMPIRE_SUMMON,
     MS_INVIS},
/*vampire knight       */
    {41,        // gave these guys a bit more than "rats and bats" -- bwr
     MS_VAMPIRE_SUMMON,
     MS_PARALYSIS,
     MS_HASTE,
     MS_HEAL,
     MS_VAMPIRE_SUMMON,
     MS_INVIS},
/*vampire mage          */
    {42,
     MS_NEGATIVE_BOLT,
     MS_PAIN,
     MS_INVIS,
     MS_ANIMATE_DEAD,
     MS_ANIMATE_DEAD,
     MS_BLINK},
/*efreet               */
    {50,
     MS_FIRE_BOLT,
     100,
     100,
     MS_FIREBALL,
     100,
     100},
/*brain worm           */
    {52,
     MS_BRAIN_FEED,
     100,
     100,
     MS_BRAIN_FEED,
     100,
     100},
/*giant orange brain   */
    {53,
     MS_BRAIN_FEED,
     MS_MUTATION,
     MS_CONFUSE,
     MS_LEVEL_SUMMON,
     MS_BLINK,
     MS_TELEPORT},
/*R                    */
    {54,
     MS_FAKE_RAKSHASA_SUMMON,
     MS_BLINK,
     MS_INVIS,
     MS_FAKE_RAKSHASA_SUMMON,
     MS_BLINK,
     MS_TELEPORT},
/*GooE                 */
    {55,
     MS_PARALYSIS,
     MS_DISINTEGRATE,
     100,
     MS_SLOW,
     MS_CONFUSE,
     MS_TELEPORT_OTHER},
/*orc sorceror         */
    {56,
     MS_FIRE_BOLT,
     MS_NEGATIVE_BOLT,
     MS_SUMMON_DEMON,
     52,
     20,
     MS_TELEPORT},
/*steam dragon         */
    {57,
     MS_STEAM_BALL,
     MS_STEAM_BALL,
     100,
     MS_STEAM_BALL,
     MS_STEAM_BALL,
     100},
/*hell knight          */
    {58,
     100,
     MS_PAIN,
     MS_HASTE,
     100,
     100,
     100},
/*hell knight          */
    {59,
     100,
     MS_FIRE_BOLT,
     100,
     100,
     100,
     MS_BLINK},
/*necromancer          */
    {60,
     MS_COLD_BOLT,
     MS_NEGATIVE_BOLT,
     100,
     MS_ANIMATE_DEAD,
     MS_ANIMATE_DEAD,
     MS_TELEPORT},
/*necromancer          */
    {61,
     MS_FIRE_BOLT,
     MS_PAIN,
     MS_INVIS,
     MS_ANIMATE_DEAD,
     MS_ANIMATE_DEAD,
     MS_BLINK},
/*wizard               */
    {62,
     MS_MMISSILE,
     MS_PARALYSIS,
     MS_HASTE,
     MS_LIGHTNING_BOLT,
     MS_CONFUSE,
     MS_TELEPORT},
/*wizard               */
    {63,
     MS_VENOM_BOLT,
     MS_ORB_ENERGY,
     MS_INVIS,
     MS_CONFUSE,
     MS_SLOW,
     MS_TELEPORT},
/*wizard               */
    {64,
     MS_PARALYSIS,
     MS_CRYSTAL_SPEAR,
     MS_BLINK,
     MS_FIRE_BOLT,
     MS_COLD_BOLT,
     MS_HEAL},
/*wizard               */
    {65,
     MS_STONE_ARROW,
     MS_STING,
     MS_BLINK,
     MS_LIGHTNING_BOLT,
     MS_BANISHMENT,
     MS_HEAL},
/*wizard               */
    {66,
     MS_PARALYSIS,
     MS_FLAME,
     MS_INVIS,
     MS_TELEPORT_OTHER,
     MS_FIREBALL,
     MS_INVIS},
/*orc priest           */
    {67,
     MS_PAIN,
     100,
     MS_SMITE,
     100,
     100,
     MS_HEAL},
/*orc high priest      */
    {68,
     MS_PAIN,
     MS_SUMMON_DEMON,
     MS_SMITE,
     MS_SUMMON_DEMON,
     MS_ANIMATE_DEAD,
     MS_HEAL},
/*mottled D            */
    {69,
     MS_STICKY_FLAME,
     MS_STICKY_FLAME,
     100,
     100,
     100,
     100},
/*Ice Fiend            */
    {70,
     MS_COLD_BOLT,
     MS_COLD_BOLT,
     MS_TORMENT,
     100,
     100,
     MS_SUMMON_DEMON},
/*Shadow Fiend         */
    {71,
     MS_COLD_BOLT,
     MS_NEGATIVE_BOLT,
     MS_TORMENT,
     100,
     100,
     MS_SUMMON_DEMON},
/*tormentor            */
    {72,
     MS_PAIN,
     100,
     100,
     100,
     100,
     100},
/*Storm D + vapour     */
    {73,
     MS_LIGHTNING_BOLT,
     MS_LIGHTNING_BOLT,
     100,
     MS_LIGHTNING_BOLT,
     MS_LIGHTNING_BOLT,
     100},
/*WHITE lesser demon   */
    {74,
     MS_FROST,
     100,
     100,
     100,
     100,
     100},
/*CYAN demon           */
    {75,
     100,
     MS_IRON_BOLT,
     MS_SUMMON_UFETUBUS,
     100,
     MS_SUMMON_UFETUBUS,
     100},
/*MAGENTA demon        */
    {76,
     MS_MUTATION,
     100,
     100,
     MS_BRAIN_FEED,
     MS_SUMMON_DEMON_LESSER,
     100},
/*LIGHTGRAY demon (227) */
    {77,
     100,
     100,
     100,
     MS_TELEPORT_OTHER,
     MS_ANIMATE_DEAD,
     MS_TELEPORT},
/*LIGHTGRAY demon (228) */
    {78,
     MS_STICKY_FLAME,
     MS_STEAM_BALL,
     MS_SMITE,
     100,
     100,
     100},
/*BROWN greater demon       */
    {79,
     MS_SUMMON_DEMON_LESSER,
     MS_SUMMON_DEMON_LESSER,
     MS_MUTATION,
     MS_SUMMON_DEMON_LESSER,
     MS_DIG,
     100},
/*GREEN greater demon  */
    {80,
     MS_POISON_BLAST,
     MS_POISON_BLAST,
     100,
     MS_VENOM_BOLT,
     MS_SUMMON_DEMON_LESSER,
     MS_BLINK},
/*RED gr demon (233)   */
    {81,
     MS_FIRE_BOLT,
     MS_FIREBALL,
     100,
     MS_STICKY_FLAME,
     MS_SMITE,
     MS_TELEPORT},
/*BLUE gr demon        */
    {82,
     MS_LIGHTNING_BOLT,
     MS_COLD_BOLT,
     100,
     MS_SUMMON_DEMON_LESSER,
     MS_LEVEL_SUMMON,
     MS_TELEPORT_OTHER},
/*Geryon               */
    {83,
     MS_SUMMON_BEAST,
     100,
     MS_SUMMON_BEAST,
     MS_SUMMON_BEAST,
     100,
     MS_SUMMON_BEAST},
/*Dispater             */
    {84,
     MS_SUMMON_DEMON_GREATER,
     MS_IRON_BOLT,
     MS_SUMMON_DEMON,
     MS_LIGHTNING_BOLT,
     MS_HELLFIRE,
     MS_SUMMON_DEMON},
/*Asmodeus             */
    {85,
     MS_FIRE_BOLT,
     MS_HELLFIRE,
     MS_SUMMON_DEMON,
     MS_SUMMON_DEMON_GREATER,
     MS_NEGATIVE_BOLT,
     MS_TELEPORT},
/*Ereshkigal           */
    {86,
     MS_NEGATIVE_BOLT,
     MS_COLD_BOLT,
     MS_SUMMON_DEMON,
     MS_PAIN,
     MS_PARALYSIS,
     MS_HEAL},
/*Antaeus              */
    {87,
     MS_COLD_BOLT,
     MS_LIGHTNING_BOLT,
     100,
     100,
     100,
     100},
/*Nemelex Xobeh        */
    {90,
     MS_SUMMON_DEMON,
     MS_SMITE,
     MS_INVIS,
     MS_MUTATION,
     MS_LEVEL_SUMMON,
     MS_TELEPORT},
/*Sif Muna             */
    {91,
     MS_LIGHTNING_BOLT,
     MS_COLD_BOLT,
     MS_SUMMON_DEMON,
     MS_BLINK,
     MS_TELEPORT,
     MS_HEAL},
/*Okawaru              */
    {92,
     MS_FIRE_BOLT,
     MS_IRON_BOLT,
     100,
     MS_FIREBALL,
     MS_SUMMON_DEMON_LESSER,
     100},
/*Kikubaaqudgha        */
    {93,
     MS_POISON_BLAST,
     MS_SLOW,
     100,
     MS_NEGATIVE_BOLT,
     MS_SUMMON_DEMON,
     MS_SUMMON_DEMON},
/*Titan                */
    {94,
     MS_LIGHTNING_BOLT,
     100,
     100,
     100,
     100,
     MS_HEAL},
/*Golden dragon        */
    {95,
     MS_FIRE_BOLT,
     MS_COLD_BOLT,
     100,
     100,
     MS_POISON_BLAST,
     100},
/*deep elf summoner    */
    {96,
     MS_BLINK,
     MS_SUMMON_DEMON_LESSER,
     MS_SUMMON_UFETUBUS,
     MS_VAMPIRE_SUMMON,
     MS_SUMMON_DEMON,
     MS_TELEPORT},
/*deep elf conjurer    */
    {97,
     MS_FIRE_BOLT,
     MS_COLD_BOLT,
     100,
     MS_LIGHTNING_BOLT,
     MS_STICKY_FLAME,
     MS_TELEPORT},
/*deep elf conjurer 2  */
    {98,
     MS_STICKY_FLAME,
     MS_ORB_ENERGY,
     MS_INVIS,
     MS_STONE_ARROW,
     MS_NEGATIVE_BOLT,
     MS_TELEPORT},
/*deep elf priest      */
    {99,
     MS_PAIN,
     100,
     MS_SMITE,
     MS_HEAL,
     MS_ANIMATE_DEAD,
     MS_HEAL},
/*deep elf high priest */
    {100,
     MS_SUMMON_DEMON,
     MS_HELLFIRE_BURST,
     MS_SMITE,
     MS_HEAL,
     MS_ANIMATE_DEAD,
     MS_HEAL},
/*deep elf demonologist */
    {101,
     MS_SUMMON_DEMON,
     MS_BANISHMENT,
     MS_SUMMON_DEMON_GREATER,
     MS_SUMMON_DEMON,
     MS_SUMMON_DEMON_LESSER,
     MS_TELEPORT},
/*deep elf annihilator */
    {102,
     MS_LIGHTNING_BOLT,
     MS_CRYSTAL_SPEAR,
     MS_BLINK,
     MS_IRON_BOLT,
     MS_POISON_BLAST,
     MS_TELEPORT},
/*deep elf sorceror    */
    {103,
     MS_NEGATIVE_BOLT,
     MS_PARALYSIS,
     MS_HASTE,
     MS_SUMMON_DEMON,
     MS_ANIMATE_DEAD,
     MS_TELEPORT},
/*deep elf death mage  */
    {104,
     MS_NEGATIVE_BOLT,
     MS_NEGATIVE_BOLT,
     MS_HEAL,
     MS_ANIMATE_DEAD,
     MS_ANIMATE_DEAD,
     MS_TELEPORT},
/*kobold demonologist  */
    {105,
     MS_SUMMON_DEMON_LESSER,
     MS_SUMMON_DEMON,
     MS_SUMMON_DEMON_LESSER,
     MS_SUMMON_DEMON,
     100,
     100},
/*naga                 */
    {106,
     MS_POISON_SPLASH,
     MS_POISON_SPLASH,
     100,
     100,
     100,
     100},
/*naga mage            */
    {107,
     MS_VENOM_BOLT,
     MS_ORB_ENERGY,
     MS_HASTE,
     MS_VENOM_BOLT,
     MS_TELEPORT_OTHER,
     MS_TELEPORT},
/*curse skull          */
    {108,
     MS_SUMMON_UNDEAD,
     MS_SUMMON_UNDEAD,
     MS_TORMENT,
     100,
     MS_SUMMON_UNDEAD,
     100},
/*shining eye          */
    {109,
     MS_MUTATION,
     MS_MUTATION,
     100,
     100,
     100,
     100},
/*frost giant          */
    {110,
     MS_COLD_BOLT,
     MS_COLD_BOLT,
     100,
     100,
     100,
     100},
/*Angel                */
    {111,
     100,
     100,
     MS_HEAL,
     100,
     MS_HEAL,
     MS_HEAL},
/*Daeva                */
    {112,
     MS_SMITE,
     100,
     MS_SMITE,
     100,
     MS_SMITE,
     100},
/*Shadow Dragon        */
    {113,
     MS_NEGATIVE_BOLT,
     MS_NEGATIVE_BOLT,
     100,
     100,
     MS_NEGATIVE_BOLT,
     100},
/*Sphinx               */
    {114,
     MS_CONFUSE,
     MS_PARALYSIS,
     MS_SMITE,
     MS_SLOW,
     100,
     MS_HEAL},
/*Mummy                */
    {115,
     MS_SUMMON_DEMON,
     MS_SMITE,
     MS_TORMENT,
     MS_SMITE,
     MS_PAIN,
     100},
/* Electric golem      */
    {116,
     MS_LIGHTNING_BOLT,
     MS_LIGHTNING_BOLT,
     MS_BLINK,
     MS_LIGHTNING_BOLT,
     MS_LIGHTNING_BOLT,
     MS_BLINK},
/* Orb of Fire         */
    {117,
     MS_FIRE_BOLT,
     MS_FIRE_BOLT,
     MS_MUTATION,
     MS_FIREBALL,
     MS_FIREBALL,
     MS_FIREBALL},
/*Shadow imp           */
    {118,
     MS_PAIN,
     100,
     MS_ANIMATE_DEAD,
     MS_ANIMATE_DEAD,
     100,
     100},
/*Ghost - in struct    */
    {119,
     100,
     100,
     100,
     100,
     100,
     100},
/*Hell-hog             */
    {120,
     MS_STICKY_FLAME,
     MS_STICKY_FLAME,
     100,
     100,
     100,
     100},
/*Swamp Dragon         */
    {121,
     MS_POISON_BLAST,
     MS_POISON_BLAST,
     100,
     MS_POISON_BLAST,
     MS_POISON_BLAST,
     100},
/*Swamp Drake          */
    {122,
     MS_MARSH_GAS,
     MS_MARSH_GAS,
     100,
     MS_MARSH_GAS,
     MS_MARSH_GAS,
     100},
/*Serpent of Hell      */
    {123,
     MS_HELLFIRE,
     MS_HELLFIRE,
     MS_HELLFIRE,
     MS_HELLFIRE,
     MS_HELLFIRE,
     MS_HELLFIRE},
/*Boggart              */
    {124,
     MS_CONFUSE,
     MS_SLOW,
     MS_INVIS,
     MS_BLINK,
     MS_LEVEL_SUMMON,
     MS_BLINK},
/*Eye of Devastation   */
    {125,
     MS_ENERGY_BOLT,
     MS_ENERGY_BOLT,
     MS_ENERGY_BOLT,
     MS_ENERGY_BOLT,
     MS_ENERGY_BOLT,
     MS_ENERGY_BOLT},
/*Quicksilver dragon   */
    {126,
     MS_QUICKSILVER_BOLT,
     MS_QUICKSILVER_BOLT,
     100,
     MS_QUICKSILVER_BOLT,
     MS_QUICKSILVER_BOLT,
     100},
/*Iron dragon          */
    {127,
     MS_METAL_SPLINTERS,
     MS_METAL_SPLINTERS,
     100,
     MS_METAL_SPLINTERS,
     MS_METAL_SPLINTERS,
     100},
/*Skeletal warrior     */
    {128,
     MS_ANIMATE_DEAD,
     100,
     MS_ANIMATE_DEAD,
     100,
     100,
     100},

#endif
